# Generated by Django 5.2.1 on 2025-05-27 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('passport_photo', models.ImageField(upload_to='photos/')),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('surety_name', models.CharField(max_length=100)),
                ('surety_nrc', models.CharField(max_length=20)),
                ('surety_phone', models.CharField(max_length=20)),
                ('witness_name', models.CharField(max_length=100)),
                ('witness_nrc', models.CharField(max_length=20)),
                ('witness_phone', models.CharField(max_length=20)),
                ('days_to_pay', models.PositiveIntegerField(default=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
