# Generated by Django 5.2.1 on 2025-06-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_payment_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='client',
            name='days_to_pay',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_to_pay', models.PositiveIntegerField(default=30)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='clients.client')),
            ],
        ),
    ]
