# Generated by Django 5.2.1 on 2025-06-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_payment_client_payment_loan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
