# Generated by Django 5.2.1 on 2025-06-26 08:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='days_to_pay',
        ),
        migrations.AddField(
            model_name='loan',
            name='exempt_day',
            field=models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='SUNDAY', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('37.8'), max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_days_created',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LoanRepaymentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_days', to='clients.loan')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('loan', 'day_number')},
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
