# Generated by Django 5.2.1 on 2025-07-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_loan_days_to_pay_loan_exempt_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
