# Generated by Django 5.2.1 on 2025-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_loanrepaymentday_corrected_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
