# Generated by Django 5.2.1 on 2025-07-12 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_client_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='content',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='title',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='accumulative_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='advance_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='clients_owing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='optional_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_expected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
