# Generated by Django 5.2.1 on 2025-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_remove_dailyreport_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrepaymentday',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid on this day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrepaymentday',
            name='balance_carried_forward',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shortfall forwarded to next unpaid day', max_digits=10, null=True),
        ),
    ]
