# Generated by Django 5.2.1 on 2025-07-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_client_address_client_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='surety_nrc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surety_phone',
        ),
    ]
